package com.ayaz.core.enums;

import java.util.Arrays;
import java.util.List;

import static com.ayaz.core.enums.EOperator.*;


public enum EFieldType {

    VERSION(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT, WAS, WAS_IN, WAS_NOT, WAS_NOT_IN, CHANGED),
    USER(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN, WAS, WAS_IN, WAS_NOT, WAS_NOT_IN, CHANGED),
    CATEGORY(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    TEXT(CONTAINS, DOES_NOT_CONTAIN, IS, IS_NOT),
    COMPONENT(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    DATE(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT),
    FILTER(EQUALS, NOT_EQUALS, IN, NOT_IN),
    ISSUE(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT),
    SECURITY_LEVEL(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    DURATION(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT),
    PRIORITY(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT, WAS, WAS_IN, WAS_NOT, WAS_NOT_IN, CHANGED),
    PROJECT(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    RESOLUTION(EQUALS, NOT_EQUALS, LESS_THAN, LESS_THAN_EQUALS, IN, NOT_IN, GREATER_THAN, GREATER_THAN_EQUALS, IS, IS_NOT, WAS, WAS_IN, WAS_NOT, WAS_NOT_IN, CHANGED),
    NUMBER(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    STATUS(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN, WAS, WAS_IN, WAS_NOT, WAS_NOT_IN, CHANGED),
    TEXT_MASTER(CONTAINS),
    ISSUE_TYPE(EQUALS, NOT_EQUALS, IS, IS_NOT, IN, NOT_IN),
    CUSTOM_TYPE;

    private final List<EOperator> supportedOperators;

    EFieldType(EOperator... supportedOperators) {
        this.supportedOperators = Arrays.asList(supportedOperators);
    }

    public List<EOperator> getSupportedOperators() {
        return supportedOperators;
    }
}
